import React from 'react';

const SummaryCard = ({ flashcards, quiz, metadata, onStartFlashcards, onTakeQuiz }) => {
  const flashcardCount = flashcards?.length || 0;
  const quizCount = quiz?.length || 0;
  
  // Estimate: 1 minute per 2 flashcards, 1 minute per 2 quiz questions
  const estimatedTime = Math.ceil((flashcardCount / 2) + (quizCount / 2));

  return (
    <div className="w-full max-w-2xl mx-auto bg-white rounded-3xl p-8 border border-gray-100 shadow-sm animate-slide-up">
      <div className="text-center mb-8">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-indigo-50 text-indigo-600 mb-6 shadow-sm">
          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
          </svg>
        </div>
        <h2 className="text-3xl font-bold text-dark mb-2">Study Material Ready</h2>
        <p className="text-gray-500">Your AI-generated flashcards and quiz are prepared.</p>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-8">
        <div className="bg-gray-50 rounded-2xl p-5 border border-gray-100/50">
          <div className="text-gray-500 text-sm font-medium mb-1 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
            Flashcards
          </div>
          <div className="text-3xl font-bold text-dark">{flashcardCount}</div>
        </div>
        <div className="bg-gray-50 rounded-2xl p-5 border border-gray-100/50">
          <div className="text-gray-500 text-sm font-medium mb-1 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            Quiz Questions
          </div>
          <div className="text-3xl font-bold text-dark">{quizCount}</div>
        </div>
        <div className="bg-gray-50 rounded-2xl p-5 border border-gray-100/50">
          <div className="text-gray-500 text-sm font-medium mb-1 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            Estimated Time
          </div>
          <div className="text-3xl font-bold text-dark">{estimatedTime} min</div>
        </div>
        <div className="bg-gray-50 rounded-2xl p-5 border border-gray-100/50">
          <div className="text-gray-500 text-sm font-medium mb-1 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
            Difficulty
          </div>
          <div className="text-2xl font-bold text-dark">{metadata?.difficulty || 'Medium'}</div>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 mb-8">
        <button
          onClick={onStartFlashcards}
          className="flex-1 bg-dark text-white rounded-xl py-4 font-medium hover:bg-gray-800 transition-colors shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-dark"
        >
          Start Flashcards
        </button>
        <button
          onClick={onTakeQuiz}
          className="flex-1 bg-white text-dark border border-gray-200 rounded-xl py-4 font-medium hover:bg-gray-50 transition-colors shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-200"
        >
          Take Quiz
        </button>
      </div>

      {metadata && (
        <div className="pt-6 border-t border-gray-100 flex flex-wrap justify-center gap-x-8 gap-y-2 text-xs text-gray-400">
          <div className="flex items-center gap-1.5">
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
            Generated by {metadata.provider}
          </div>
          <div className="flex items-center gap-1.5">
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            Time: {(metadata.generationTimeMs / 1000).toFixed(2)}s
          </div>
          <div className="flex items-center gap-1.5">
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
            Just Now
          </div>
        </div>
      )}
    </div>
  );
};

export default SummaryCard;
